version: 1.0.0
environment:
  matrix:
    - JAVA_VERSION: 8 # Или нужная версия Java
      BROWSER: chrome # Или firefox, edge и т.д.

install:
  - ps: Install-Product -Name Chocolatey
  - choco install chromedriver -version 114.0.5735.90  # Или нужная версия ChromeDriver.  Подберите версию
    #под вашу версию Chrome.  Проверьте в документации Appveyor
    # и Selenium
  - ps: Set-EnvironmentVariable -Name CHROME_DRIVER -Value "C:\Program Files\ChromeDriver\chromedriver.exe"
  # (или путь к chromedriver  после установки через Chocolatey)

build: off # Не нужна отдельная фаза сборки

test:
  -Name URL_SITE -Value "https://only.digital/" 

# Важно! Замените:
# - ".;path\to\junit\jar;path\to\selenium\jar;path\to\selenide\jar"   на правильный classpath,
#   соответствующий структуре вашего проекта.
# -  org.junit.runner.JUnitCore YourTestClass на имя вашего класса теста
